create table vaccinations (
	vaccination_id INT,
	citizen_id INT,
	vaccination_type VARCHAR(17),
	date_administered DATE,
	    FOREIGN KEY (citizen_id) REFERENCES citizens(citizen_id)
);
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (1, 829, 'Johnson & Johnson', '1/2/2012');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (2, 549, 'Moderna', '8/21/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (3, 90, 'Johnson & Johnson', '8/17/2013');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (4, 722, 'AstraZeneca', '4/23/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (5, 604, 'Sinovac', '11/19/2005');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (6, 28, 'Pfizer', '11/24/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (7, 5, 'Johnson & Johnson', '1/30/2015');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (8, 124, 'AstraZeneca', '6/24/2003');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (9, 114, 'Johnson & Johnson', '3/10/2005');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (10, 687, 'Moderna', '5/17/2017');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (11, 715, 'Sputnik V', '7/31/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (12, 871, 'Sinovac', '7/7/2003');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (13, 134, 'Sputnik V', '4/16/2004');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (14, 719, 'Sinovac', '10/5/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (15, 921, 'Pfizer', '4/23/2017');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (16, 610, 'Pfizer', '3/7/2020');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (17, 334, 'Sputnik V', '5/8/2021');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (18, 545, 'Pfizer', '3/26/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (19, 940, 'Moderna', '5/10/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (20, 210, 'Pfizer', '1/2/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (21, 316, 'Johnson & Johnson', '5/19/2018');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (22, 533, 'Moderna', '8/1/2000');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (23, 491, 'Moderna', '3/12/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (24, 12, 'Pfizer', '4/16/2022');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (25, 517, 'Sputnik V', '11/4/2001');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (26, 814, 'Johnson & Johnson', '6/27/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (27, 641, 'AstraZeneca', '12/28/2004');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (28, 850, 'Pfizer', '3/16/2003');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (29, 907, 'Pfizer', '11/17/2001');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (30, 993, 'Moderna', '9/2/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (31, 228, 'Sputnik V', '2/13/2005');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (32, 791, 'Johnson & Johnson', '1/17/2016');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (33, 128, 'Johnson & Johnson', '2/14/2016');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (34, 526, 'AstraZeneca', '5/25/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (35, 204, 'Pfizer', '6/6/2007');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (36, 905, 'Sinovac', '4/5/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (37, 852, 'Johnson & Johnson', '9/18/2006');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (38, 775, 'AstraZeneca', '7/16/2023');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (39, 240, 'Sinovac', '8/10/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (40, 810, 'Johnson & Johnson', '5/27/2023');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (41, 587, 'AstraZeneca', '3/14/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (42, 156, 'AstraZeneca', '3/21/2005');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (43, 983, 'AstraZeneca', '9/3/2021');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (44, 395, 'Johnson & Johnson', '9/21/2007');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (45, 288, 'Moderna', '3/14/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (46, 562, 'Sputnik V', '3/8/2000');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (47, 422, 'Sputnik V', '10/3/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (48, 688, 'Sputnik V', '8/30/2006');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (49, 1000, 'AstraZeneca', '11/14/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (50, 856, 'Johnson & Johnson', '6/21/2012');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (51, 159, 'Pfizer', '8/16/2017');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (52, 509, 'Johnson & Johnson', '11/25/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (53, 672, 'Sputnik V', '2/20/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (54, 140, 'Johnson & Johnson', '9/11/2001');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (55, 997, 'AstraZeneca', '10/23/2000');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (56, 964, 'Sputnik V', '9/2/2015');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (57, 121, 'Sinovac', '1/25/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (58, 98, 'Sputnik V', '6/18/2021');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (59, 121, 'Pfizer', '1/20/2022');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (60, 423, 'Sinovac', '3/7/2024');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (61, 977, 'Johnson & Johnson', '4/19/2017');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (62, 36, 'Sinovac', '10/8/2004');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (63, 204, 'Pfizer', '1/1/2011');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (64, 276, 'Pfizer', '10/21/2018');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (65, 867, 'AstraZeneca', '11/24/2012');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (66, 759, 'Sputnik V', '6/18/2007');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (67, 676, 'Sputnik V', '5/18/2009');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (68, 484, 'Sinovac', '10/18/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (69, 22, 'Sputnik V', '6/20/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (70, 944, 'Sinovac', '6/4/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (71, 246, 'Moderna', '3/26/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (72, 332, 'Pfizer', '2/24/2020');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (73, 281, 'Moderna', '7/6/2004');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (74, 926, 'Moderna', '8/5/2015');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (75, 589, 'Johnson & Johnson', '9/27/2024');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (76, 525, 'Sinovac', '7/29/2021');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (77, 941, 'Johnson & Johnson', '11/4/2001');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (78, 217, 'Sinovac', '2/11/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (79, 353, 'Johnson & Johnson', '10/9/2010');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (80, 308, 'Sputnik V', '10/31/2019');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (81, 37, 'Moderna', '9/12/2005');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (82, 356, 'Sputnik V', '11/9/2023');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (83, 653, 'Johnson & Johnson', '11/1/2003');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (84, 981, 'Sputnik V', '7/8/2015');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (85, 138, 'Sputnik V', '7/15/2006');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (86, 647, 'Sinovac', '8/5/2003');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (87, 473, 'Pfizer', '3/4/2015');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (88, 766, 'Pfizer', '2/24/2014');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (89, 877, 'Sinovac', '12/11/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (90, 834, 'Moderna', '2/26/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (91, 737, 'AstraZeneca', '12/10/2020');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (92, 373, 'Johnson & Johnson', '12/4/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (93, 270, 'Sputnik V', '4/14/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (94, 335, 'Pfizer', '8/10/2007');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (95, 403, 'Sinovac', '3/9/2021');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (96, 855, 'AstraZeneca', '5/15/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (97, 695, 'Pfizer', '6/22/2002');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (98, 488, 'Sputnik V', '4/23/2016');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (99, 811, 'Moderna', '3/10/2008');
insert into vaccinations (vaccination_id, citizen_id, vaccination_type, date_administered) values (100, 377, 'Johnson & Johnson', '7/1/2022');
